(* lib/fsm.ml *)
open Ast

(* ---------------------------------------------------------------------------
   RTL Control-Signal Model
   ---------------------------------------------------------------------------
   Instead of abstract "Latch(var, expr)" actions, every FSM state now carries
   a concrete dictionary of boolean control signals that map 1-to-1 onto
   physical wires in the generated RTL netlist.

   Signal vocabulary (all default to 0 / false unless listed in a state):

     LOAD ENABLES  – rising-edge clock enables for storage elements
       Ld_R        – load enable for Reg_R
       Ld_B        – load enable for Reg_B
       Ld_E        – load enable for SReg_E (initial write from input port)
       Shift_E     – shift-right enable for SReg_E  (separate from Ld_E)

     MUX SELECTS   – 1-bit selects on the 2-to-1 Muxes feeding each register
       MuxSel_R    – 0 = feed Reg_R from init value, 1 = feed from ALU output
       MuxSel_B    – 0 = feed Reg_B from init value, 1 = feed from ALU output

     ALU ENABLES   – activates the combinational multiplier for one cycle
       ALU_Mul     – enables the Mul ALU feeding both Reg_R and Reg_B

     STATUS WIRES (read-only; generated by Comparator watching SReg_E)
       Cmp_eqz     – 1 when SReg_E == 0  →  controls while-loop exit branch
       Cmp_is_odd  – 1 when SReg_E[0] == 1  →  controls inner if-branch

   The FSM compiler maps each AST construct to the minimal set of asserted
   signals required to implement it in one clock cycle.
   --------------------------------------------------------------------------- *)

(* A single boolean control signal: (signal_name, value).
   We store only *asserted* (true) signals; everything absent is implicitly 0.
   Keeping both name and value makes the JSON serialiser and printer simple. *)
type signal = {
  name  : string;
  value : bool;    (* always true in practice; kept for future tri-state work *)
}

(* A status-wire condition used in Branch transitions.
   Using named wires keeps the JSON human-readable and decoupled from AST exprs. *)
type condition =
  | WireHigh of string          (* branch when named status wire is 1 *)
  | ExprCond of expr            (* fallback for For-loop numeric conditions *)

type transition =
  | Goto   of int
  | Branch of condition * int * int   (* condition, true_id, false_id *)
  | Done

type state = {
  id      : int;
  label   : string;             (* human-readable name, e.g. "INIT_R" *)
  signals : signal list;        (* asserted control signals this cycle *)
  next    : transition;
}

(* ---------------------------------------------------------------------------
   State-counter (reset per generate call)
   --------------------------------------------------------------------------- *)
let state_counter = ref 0
let new_id () = let i = !state_counter in incr state_counter; i

(* Convenience: build a signal record *)
let sig_ name = { name; value = true }

(* ---------------------------------------------------------------------------
   Control-signal derivation from AST expressions
   ---------------------------------------------------------------------------
   Each Assign statement is inspected to decide which combination of load-
   enables, mux-selects, and ALU-enables must fire in that clock cycle.
   --------------------------------------------------------------------------- *)

(* Map a variable name to its load-enable signal name *)
let load_enable_of = function
  | "r" -> "Ld_R"
  | "b" -> "Ld_B"
  | "e" -> "Ld_E"
  | v   -> "Ld_" ^ String.capitalize_ascii v

(* Map a variable name to its mux-select signal name *)
let mux_sel_of = function
  | "r" -> "MuxSel_R"
  | "b" -> "MuxSel_B"
  | v   -> "MuxSel_" ^ String.capitalize_ascii v

(* Decide whether an expression requires the shared multiplier *)
let rec needs_mul = function
  | BinOp (Mul, _, _) -> true
  | BinOp (_, e1, e2) -> needs_mul e1 || needs_mul e2
  | _ -> false

(* Is this expression a right-shift of the variable itself? (e = e >> 1) *)
let is_self_shift var = function
  | BinOp (Shr, Var v, _) when v = var -> true
  | _ -> false

(* Is this expression a "simple" initialisation — i.e. a Var or Const
   that does NOT loop back through an ALU?  Used to set MuxSel. *)
let is_init_expr = function
  | Var _ | Const _ -> true
  | _ -> false

(* Derive the concrete list of asserted control signals for one Assign stmt.
   [is_loop_context] is true when we are inside a While or For body;
   it determines MuxSel (loop path vs. init path). *)
let signals_of_assign var expr ~is_loop_context =
  let ld = sig_ (load_enable_of var) in

  if is_self_shift var expr then
    (* e = e >> 1 : only the shift enable fires; no Ld (SREG handles it) *)
    [ sig_ "Shift_E" ]
  else begin
    let base = [ ld ] in

    (* MuxSel only for variables that have a Mux (i.e. assigned in >1 place) *)
    let mux_sigs =
      if is_loop_context && not (is_init_expr expr) then
        [ sig_ (mux_sel_of var) ]   (* sel = 1: route ALU output *)
      else
        []                           (* sel = 0 (default): route init value *)
    in

    (* ALU_Mul fires whenever a multiplication is in the expression *)
    let alu_sigs =
      if needs_mul expr then [ sig_ "ALU_Mul" ] else []
    in

    base @ mux_sigs @ alu_sigs
  end

(* ---------------------------------------------------------------------------
   AST → FSM compiler
   ---------------------------------------------------------------------------
   compile_block returns a flat list of states.  start_id and exit_id are
   pre-allocated by the caller so that forward/back edges can be wired up
   without a second pass.
   --------------------------------------------------------------------------- *)
let rec compile_block ?(is_loop_context = false) stmts start_id exit_id =
  match stmts with
  | [] ->
      (* Empty block: just thread through to the exit *)
      [ { id = start_id; label = "PASS"; signals = []; next = Goto exit_id } ]

  (* ── Assign ───────────────────────────────────────────────────────────── *)
  | Assign (var, expr) :: rest ->
      let next_id   = if rest = [] then exit_id else new_id () in
      let sigs      = signals_of_assign var expr ~is_loop_context in
      let lbl       =
        if is_self_shift var expr then "SHIFT_" ^ String.uppercase_ascii var
        else "LD_" ^ String.uppercase_ascii var
      in
      let cur_state = { id = start_id; label = lbl; signals = sigs; next = Goto next_id } in
      let rest_states =
        if rest = [] then []
        else compile_block ~is_loop_context rest next_id exit_id
      in
      cur_state :: rest_states

  (* ── If ───────────────────────────────────────────────────────────────── *)
  | If (cond, true_block, false_block) :: rest ->
      let true_start  = new_id () in
      let false_start = new_id () in
      let merge_id    = if rest = [] then exit_id else new_id () in

      (* Translate the if-condition to a named status wire when possible *)
      let hw_cond = condition_of_expr cond in

      let branch_state = {
        id      = start_id;
        label   = "BRANCH";
        signals = [];
        next    = Branch (hw_cond, true_start, false_start);
      } in

      let true_states  = compile_block ~is_loop_context true_block  true_start  merge_id in
      let false_states = compile_block ~is_loop_context false_block false_start merge_id in
      let rest_states  =
        if rest = [] then []
        else compile_block ~is_loop_context rest merge_id exit_id
      in
      (branch_state :: true_states) @ false_states @ rest_states

  (* ── While ────────────────────────────────────────────────────────────── *)
  | While (cond, body) :: rest ->
      (*  States:
            check_id  – evaluate comparator status wires; branch body/exit
            body_start – first state of the loop body
          The body loops back to check_id on completion. *)
      let check_id   = new_id () in
      let body_start = new_id () in
      let merge_id   = if rest = [] then exit_id else new_id () in

      let hw_cond = condition_of_expr cond in

      let check_state = {
        id      = check_id;
        label   = "WHILE_CHECK";
        signals = [];                              (* purely a control state *)
        next    = Branch (hw_cond, body_start, merge_id);
      } in

      (* Thread from start_id into the check state *)
      let entry_state = {
        id      = start_id;
        label   = "WHILE_ENTRY";
        signals = [];
        next    = Goto check_id;
      } in

      (* Body compiles with is_loop_context=true so MuxSels get set *)
      let body_states =
        compile_block ~is_loop_context:true body body_start check_id
      in

      let rest_states =
        if rest = [] then []
        else compile_block ~is_loop_context rest merge_id exit_id
      in
      (entry_state :: check_state :: body_states) @ rest_states

  (* ── For ─────────────────────────────────────────────────────────────── *)
  | For (var, start_val, stop_val, body) :: rest ->
      let check_id   = new_id () in
      let body_start = new_id () in
      let inc_id     = new_id () in
      let merge_id   = if rest = [] then exit_id else new_id () in

      let init_sigs  = signals_of_assign var start_val ~is_loop_context:false in
      let init_state = {
        id      = start_id;
        label   = "FOR_INIT_" ^ String.uppercase_ascii var;
        signals = init_sigs;
        next    = Goto check_id;
      } in

      let loop_cond  = ExprCond (BinOp (Lt, Var var, stop_val)) in
      let check_state = {
        id      = check_id;
        label   = "FOR_CHECK";
        signals = [];
        next    = Branch (loop_cond, body_start, merge_id);
      } in

      let body_states = compile_block ~is_loop_context:true body body_start inc_id in

      let inc_expr  = BinOp (Add, Var var, Const 1) in
      let inc_sigs  = signals_of_assign var inc_expr ~is_loop_context:true in
      let inc_state = {
        id      = inc_id;
        label   = "FOR_INC_" ^ String.uppercase_ascii var;
        signals = inc_sigs;
        next    = Goto check_id;
      } in

      let rest_states =
        if rest = [] then []
        else compile_block ~is_loop_context rest merge_id exit_id
      in
      [init_state; check_state] @ body_states @ [inc_state] @ rest_states

(* ---------------------------------------------------------------------------
   Condition translation
   ---------------------------------------------------------------------------
   Map an AST expression used as a branch condition onto a named hardware
   status wire where possible, falling back to ExprCond for For-loop bounds.
   --------------------------------------------------------------------------- *)
and condition_of_expr = function
  (* e > 0  →  NOT eqz  (loop continues while e ≠ 0)
     We model this as WireHigh "Cmp_not_eqz" which is the complement of eqz.
     The React visualiser can invert the wire display label. *)
  | BinOp (Gt, Var "e", Const 0) -> WireHigh "Cmp_not_eqz"
  (* e % 2 == 1  →  is_odd *)
  | BinOp (Eq, BinOp (Mod, Var "e", Const 2), Const 1) -> WireHigh "Cmp_is_odd"
  (* Generic fallback for For-loop numeric bounds *)
  | expr -> ExprCond expr

(* ---------------------------------------------------------------------------
   Public entry point
   --------------------------------------------------------------------------- *)
let generate ast =
  state_counter := 0;
  let start_id = new_id () in
  let exit_id  = new_id () in
  let states   = compile_block ast start_id exit_id in
  let halt     = { id = exit_id; label = "HALT"; signals = []; next = Done } in
  states @ [ halt ]

(* ---------------------------------------------------------------------------
   Printer
   --------------------------------------------------------------------------- *)
let string_of_condition = function
  | WireHigh w -> w ^ " == 1"
  | ExprCond e ->
      let rec s = function
        | Var v -> v
        | Const i -> string_of_int i
        | BinOp (Add, a, b) -> s a ^ " + " ^ s b
        | BinOp (Sub, a, b) -> s a ^ " - " ^ s b
        | BinOp (Mul, a, b) -> s a ^ " * " ^ s b
        | BinOp (Mod, a, b) -> s a ^ " % " ^ s b
        | BinOp (Shr, a, b) -> s a ^ " >> " ^ s b
        | BinOp (Eq,  a, b) -> s a ^ " == " ^ s b
        | BinOp (Lt,  a, b) -> s a ^ " < "  ^ s b
        | BinOp (Gt,  a, b) -> s a ^ " > "  ^ s b
      in s e

let print_fsm states =
  Printf.printf "\n--- GENERATED CONTROL PATH (FSM) ---\n";
  List.iter (fun s ->
    Printf.printf "State %d [%s]:\n" s.id s.label;
    if s.signals = [] then
      Printf.printf "  [Signals]  (none — control-only state)\n"
    else
      List.iter (fun sg ->
        Printf.printf "  [Signal]   %s = %d\n" sg.name (if sg.value then 1 else 0)
      ) s.signals;
    (match s.next with
     | Goto id ->
         Printf.printf "  [Control]  Goto State %d\n" id
     | Branch (cond, t, f) ->
         Printf.printf "  [Control]  If (%s) Goto %d Else Goto %d\n"
           (string_of_condition cond) t f
     | Done ->
         Printf.printf "  [Control]  HALT\n")
  ) states