(lang dune 3.13)
(using menhir 3.0)
(name hls_compiler)
(generate_opam_files true)
(source
 (github username/reponame))
(authors "Author Name")
(maintainers "Maintainer Name")
(license LICENSE)
(documentation https://url/to/documentation)
(package
 (name hls_compiler)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))